# Generated by Django 6.0 on 2025-12-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_category_name_category_category_name_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'published')], default='Draft', max_length=20),
        ),
    ]
